### PR TITLE
we demand extended measures

### PR DESCRIPTION
**Pull request by astro**
Repeat after me:
> Die Matekasse ist keine Kreditanstalt.

### CODE REVIEW

**Comment by nek0** [comment]
Public shaming of users? really?  
I don't see how this raises the incentive to use this service properly.

**Comment by vv01f** [comment]
alternative idea for compromize: positive reinforcement .. neutral sounds and positive ones

**Comment by astro** [comment]
Account balances are public already.

In order to enforce proper use of this service, the alternative would be forbidding negative balances.

**Comment by nek0** [comment]
Forbidding negative balances was implemented in the first draft of this software, but I have been persuaded to drop that.

Account balances are public. But the software does not shout them out loud every time someone buys something. You have to actively scrape them. That's a difference.

**Comment by vv01f** [comment]
question remains.. what would be better if negative balance is not allowed by data type/app?

would people stick easier to the rule to pay then?

**Pull request closed without merging**
